/** All utilities are scoped under #bug-tracker-root and preflight is disabled,
 *  so nothing here can leak into (or be broken by) the WordPress admin styles. */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  important: '#bug-tracker-root',
  darkMode: ['selector', '.bt-dark'],
  corePlugins: { preflight: false },
  theme: {
    fontSize: {
      '2xs': ['10.5px', '14px'],
      xs: ['11.5px', '16px'],
      sm: ['12.5px', '18px'],
      base: ['13px', '20px'],
      lg: ['15px', '22px'],
      xl: ['17px', '24px'],
      '2xl': ['20px', '28px'],
    },
    extend: {
      colors: {
        border: 'hsl(var(--bt-border))',
        input: 'hsl(var(--bt-input))',
        ring: 'hsl(var(--bt-ring))',
        background: 'hsl(var(--bt-background))',
        foreground: 'hsl(var(--bt-foreground))',
        primary: { DEFAULT: 'hsl(var(--bt-primary))', foreground: 'hsl(var(--bt-primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--bt-secondary))', foreground: 'hsl(var(--bt-secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--bt-muted))', foreground: 'hsl(var(--bt-muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--bt-accent))', foreground: 'hsl(var(--bt-accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--bt-destructive))', foreground: 'hsl(var(--bt-destructive-foreground))' },
        sidebar: 'hsl(var(--bt-sidebar))',
        success: 'hsl(var(--bt-success))',
        warning: 'hsl(var(--bt-warning))',
        info: 'hsl(var(--bt-info))',
        card: { DEFAULT: 'hsl(var(--bt-card))', foreground: 'hsl(var(--bt-card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--bt-popover))', foreground: 'hsl(var(--bt-popover-foreground))' },
      },
      borderRadius: { lg: '8px', md: '6px', sm: '4px' },
      keyframes: {
        'bt-fade': { from: { opacity: '0' }, to: { opacity: '1' } },
        'bt-pop': { from: { opacity: '0', transform: 'translate(-50%,-48%) scale(.97)' }, to: { opacity: '1', transform: 'translate(-50%,-50%) scale(1)' } },
        'bt-slide': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: { 'bt-fade': 'bt-fade .15s ease-out', 'bt-pop': 'bt-pop .18s ease-out', 'bt-slide': 'bt-slide .2s ease-out' },
    },
  },
};
